server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  data:
    redis:
      host: "localhost"
      port: 6379


springdoc:
  swagger-ui:
    path: "/docs"

